name: build-apidoc
on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - "release/**"
        paths:
            - "**.js"

    # workflow_dispatch:
jobs:
    cache:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: cache
              uses: actions/cache@v3
              id: npm-cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node
            - if: steps.npm-cache.outputs.cache-hit == 'true'
              run: echo 'npm cache hit!'
            - if: steps.npm-cache.outputs.cache-hit != 'true'
              run: echo 'npm cache missed!'
            - run: ls -al
            - run: pwd
            - name: install dependencies
              run: npm i apidoc -g
            - name: docs build
              run: |
                  apidoc -i ./ -o docs/
                  ls -al
            - name: upload
              uses: actions/upload-artifact@v3
              with:
                  name: swcamp-${{github.sha}}
                  path: docs
            - run: echo NUMBER - ${{ github.event.number }}
