name: build-apidoc
on:
    pull_request:
jobs:
    cache:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: cache
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: install dependencies
              run: npm ci
            - name: docs build
              run: |
                  npm run apidoc
                  ls -al
            - name: upload
              uses: actions/upload-artifact@v3
              with:
                  name: apidoc
                  path: docs
