name: cache-demo
on:
    workflow_dispatch:
jobs:
    cache:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: cache
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: install dependencies
              run: npm ci
            - name: docs build
              run: |
                  npm run apidoc
                  mv ./docs ./doc-${{github.sha}}
                  ls -al
            - name: Upload to s3
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: aws s3 sync --delete --region ap-northeast-2 doc-${{github.sha}} s3://khw-gitaction-test
