name: Our First Workflow
on:
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Hello, GitHub Actions!'
    pwd-ls:
        name: PWD & LS
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: ls -al
            - uses: actions/checkout@v3
            - run: ls -al
            - run: cat ./index.js
